services:
  rdembedded:
    build:
      context: .
      dockerfile: Dockerfile
    image: robotics-deployment:embedded
    container_name: rdembedded
    volumes:
      - ./rdembedded:/opt/rdembedded
    command: ["sleep", "infinity"]
