services:
  rdembedded:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    image: robotics-deployment:embedded
    container_name: rdembedded
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./rdembedded:/opt/rdembedded
    command: ["sleep", "infinity"]
