services:
  rdembedded:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE: ${IMAGE:-robotics-deployment:dev}
    image: robotics-deployment:embedded
    privileged: true
    container_name: rdembedded
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - .:/opt/rdembedded
      - ~/.gitconfig:/home/dev/.gitconfig
      - ~/.config/lvim:/home/dev/.config/lvim
      - ~/.config/github-copilot:/home/dev/.config/github-copilot
      - ~/.local/state/lvim:/home/dev/.local/state/lvim
      - ~/.local/share/lvim:/home/dev/.local/share/lvim
      - ~/.local/share/lunarvim:/home/dev/.local/share/lunarvim
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: ["sleep", "infinity"]

