name: Build

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Build environment
    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    # Compile and strip binaries
    - name: Build x86_64
      run: docker exec rdembedded cargo build --release --bin rdembedded-x86_64 --target x86_64-unknown-linux-gnu

    - name: Strip x86_64
      run: docker exec rdembedded x86_64-linux-gnu-strip target/x86_64-unknown-linux-gnu/release/rdembedded-x86_64

    - name: Build arm64
      run: docker exec rdembedded cargo build --release --bin rdembedded-aarch64 --target aarch64-unknown-linux-gnu

    - name: Strip arm64
      run: docker exec rdembedded aarch64-linux-gnu-strip target/aarch64-unknown-linux-gnu/release/rdembedded-aarch64

    # Cleanup environment
    - name: Stop Docker Compose services
      run: docker-compose -f docker-compose.yml down

    # Upload artifacts
    - uses: actions/upload-artifact@v3
      with:
        name: rdembedded-x86_64
        path: |
          rdembedded/target/x86_64-unknown-linux-gnu/release/rdembedded-x86_64

    - uses: actions/upload-artifact@v3
      with:
        name: rdembedded-aarch64
        path: |
          rdembedded/target/aarch64-unknown-linux-gnu/release/rdembedded-aarch64

    # Create GitHub Release
    - name: Generate Tag Name
      id: generate_tag
      run: echo "::set-output name=tag_name::v$(date +'%Y%m%d%H%M%S')"

    - name: Create Git Tag
      run: git tag ${{ steps.generate_tag.outputs.tag_name }}

    - name: Push Git Tag
      run: git push origin ${{ steps.generate_tag.outputs.tag_name }}

    # Release And Upload Binaries
    - name: Create GitHub Release and Upload Binaries
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: |
          ./rdembedded/target/*/release/rdembedded-*
          ./LICENSE
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ steps.generate_tag.outputs.tag_name }}
        name: Release ${{ steps.generate_tag.outputs.tag_name }}
        body: Automated release of ${{ github.sha }}
