name: Build

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Build amd64
      run: docker exec rdembedded cargo build --release --bin rdembedded-amd64 --target x86_64-unknown-linux-gnu

    - name: Strip amd64
      run: docker exec rdembedded x86_64-linux-gnu-strip target/x86_64-unknown-linux-gnu/release/rdembedded-amd64

    - name: Build arm64
      run: docker exec rdembedded cargo build --release --bin rdembedded-aarch64 --target aarch64-unknown-linux-gnu

    - name: Strip arm64
      run: docker exec rdembedded aarch64-linux-gnu-strip target/aarch64-unknown-linux-gnu/release/rdembedded-aarch64

    - name: Stop Docker Compose services
      run: docker-compose -f docker-compose.yml down

    - uses: actions/upload-artifact@v3
      with:
        name: rdembedded-amd64
        path: |
          rdembedded/target/x86_64-unknown-linux-gnu/release/rdembedded-amd64

    - uses: actions/upload-artifact@v3
      with:
        name: rdembedded-aarch64
        path: |
          rdembedded/target/aarch64-unknown-linux-gnu/release/rdembedded-aarch64

    - name: Release
      uses: softprops/gh-release@v1
      with:
        files: rdembedded/target/*/release/rdembedded-*
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.sha }}
        name: Release ${{ github.sha }}
        body: Automated release of ${{ github.sha }}