name: Build

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Build amd64
      run: docker exec rdembedded cargo build --release --bin rdembedded-amd64 --target x86_64-unknown-linux-gnu

    - name: Strip amd64
      run: docker exec rdembedded x86_64-linux-gnu-strip target/x86_64-unknown-linux-gnu/release/rdembedded-amd64

    - name: Build arm64
      run: docker exec rdembedded cargo build --release --bin rdembedded-aarch64 --target aarch64-unknown-linux-gnu

    - name: Strip arm64
      run: docker exec rdembedded aarch64-linux-gnu-strip target/aarch64-unknown-linux-gnu/release/rdembedded-aarch64

    - name: Stop Docker Compose services
      run: docker-compose -f docker-compose.yml down

    - uses: actions/upload-artifact@v3
      with:
        name: rdembedded
        path: |
          target/x86_64-unknown-linux-gnu/release/rdembedded-amd64
          target/aarch64-unknown-linux-gnu/release/rdembedded-aarch64
