name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  docker:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build
      
    - name: Build
      run: docker exec rdembedded cargo build --verbose --release

    - name: Stop Docker Compose services
      run: docker-compose -f docker-compose.yaml down
